import { createSlice } from '@reduxjs/toolkit';
import axios from 'axios';

const initialState = {
    feeling: '',
    understanding: '',
    support: '',
    comments: '',
};

const feedbackSlice = createSlice({ // Creates a slice of the feedback state and generates actions for each reducer
    name: 'feedback',
    initialState,
    reducers: {
        setFeeling: (state, action) => {
            state.feeling = action.payload;
        },
        setUnderstanding: (state, action) => {
            state.understanding = action.payload;
        },
        setSupport: (state, action) => {
            state.support = action.payload;
        },
        setComments: (state, action) => {
            state.comments = action.payload;
        },
        resetFeedback: (state) => {
            state.feeling = initialState.feeling; // Resets the feedback state to the initial state
            state.understanding = initialState.understanding;
            state.support = initialState.support;
            state.comments = initialState.comments;
        },
    },
});

export const { // Exports the actions generated by createSlice()
    setFeeling,
    setUnderstanding,
    setSupport,
    setComments,
    resetFeedback,
} = feedbackSlice.actions;


export const submitFeedback = (feedback) => async (dispatch) => { // Async action that sends feedback data to the server for storage
    try {
        const response = await axios.post("/api/feedback", feedback);
        if (response.status === 201) {
            return true; // Returns true if the feedback was successfully saved
        } else {
            console.error("Failed to submit feedback:", response.status, response.data);
            return false;
        }
    } catch (error) {
        console.error("Failed to submit feedback:",error);
        return false;
    }
};

export default feedbackSlice.reducer;